from pathlib import Path

import pygame

BASE_DIR = Path(__file__).resolve().parent
LEVELS_DIR = BASE_DIR / "levels"
DIALOGUES_DIR = BASE_DIR / "dialogues"
ASSETS_DIR = BASE_DIR / "assets"
CHARACTERS_DIR = ASSETS_DIR / "characters"
TILES_DIR = ASSETS_DIR / "tiles"
PLAYER_ASSETS_DIR = CHARACTERS_DIR / "player"
PLAYER_IDLE_SPRITE = PLAYER_ASSETS_DIR / "weasel_hero_idle.png"
PLAYER_RUN_RIGHT_SPRITE = PLAYER_ASSETS_DIR / "weasel_hero_run_right.png"
PLAYER_DASH_RIGHT_SPRITE = PLAYER_ASSETS_DIR / "weasel_hero_dash_right.png"
PLAYER_JUMP_RIGHT_SPRITE = PLAYER_ASSETS_DIR / "weasel_hero_jump_right.png"
PLAYER_WALK_RIGHT_SPRITE = PLAYER_ASSETS_DIR / "weasel_walk_right.png"
PLAYER_WALK_UP_SPRITE = PLAYER_ASSETS_DIR / "weasel_walk_up.png"
PLAYER_WALK_DOWN_SPRITE = PLAYER_ASSETS_DIR / "weasel_walk_down.png"

# Размеры экрана
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
TILE_SIZE = 64
PLAYER_SIZE = 64
PLAYER_HITBOX_WIDTH = 45
PLAYER_HITBOX_HEIGHT = 45
PLAYER_HITBOX_OFFSET_X = 12
PLAYER_HITBOX_OFFSET_Y = 20
PLAYER_INTERACTION_WIDTH = 72
PLAYER_INTERACTION_HEIGHT = 72
PLAYER_INTERACTION_OFFSET_X = -4
PLAYER_INTERACTION_OFFSET_Y = -4
DEV_MODE = True
DEBUG_SHOW_HITBOXES = True
DEBUG_SHOW_INTERACTION_ZONES = True
DEBUG_SHOW_ENEMY_ATTACK_RADII = True
SHOW_HITBOXES = DEV_MODE and DEBUG_SHOW_HITBOXES
SHOW_INTERACTION_ZONES = DEV_MODE and DEBUG_SHOW_INTERACTION_ZONES
SHOW_ENEMY_ATTACK_RADII = DEV_MODE and DEBUG_SHOW_ENEMY_ATTACK_RADII

# Отсечение и моделирование фона. 
# Поля измеряются в пикселях мирового пространства за пределами текущего окна просмотра камеры.
RENDER_CULL_MARGIN = 160
ENEMY_FULL_UPDATE_MARGIN = 512
ENEMY_BACKGROUND_UPDATE_MARGIN = 1280
ENEMY_BACKGROUND_UPDATE_INTERVAL = 0.25

# Инвентарь
PLAYER_INVENTORY_CAPACITY = 10
HOTBAR_SIZE = 5
INVENTORY_COLUMNS = 5
INVENTORY_ROWS = 2

# Цвета (RGB)
COLORS = {
    'GRASS': (34, 139, 34),
    'WALL': (139, 69, 19),
    'WATER': (65, 105, 225),
    'PATH': (210, 180, 140),
    'STONE': (128, 128, 128),
    'PLAYER': (255, 0, 0),
    'HEALTH': (255, 0, 0),
    'HEALTH_BG': (100, 0, 0),
    'STAMINA': (255, 255, 0),
    'STAMINA_BG': (50, 50, 0),
    'WHITE': (255, 255, 255),
    'BLACK': (0, 0, 0),
    'HITBOX': (64, 224, 208),
    'INTERACTION_ZONE': (0, 255, 255),
    'SOLID_OBJECT': (110, 110, 110),
    'INTERACTABLE_OBJECT': (255, 180, 70),
    'INTERACTABLE_ACTIVE': (255, 235, 120),
    'PICKABLE_OBJECT': (90, 200, 255),
    'PICKABLE_PICKED': (170, 230, 255),
    'UI_BG': (20, 20, 28),
    'UI_PANEL': (34, 34, 44),
    'UI_PANEL_ALT': (44, 44, 58),
    'UI_SLOT': (60, 60, 76),
    'UI_SLOT_BORDER': (110, 110, 135),
    'UI_SLOT_SELECTED': (120, 180, 255),
    'UI_TEXT_DIM': (190, 190, 200),
    'GOLD': (240, 200, 70),
    'EQUIP_SLOT': (90, 90, 110),
    'EQUIP_SLOT_FILLED': (120, 160, 210),
}

# Параметры игрока
PLAYER_MAX_HEALTH = 100
PLAYER_MAX_STAMINA = 100
PLAYER_SPEED = 200
PLAYER_RUN_SPEED = 350
STAMINA_REGEN = 10
STAMINA_RUN_COST = 1
STAMINA_JUMP_COST = 1
STAMINA_DASH_COST = 25
ATTACK_COST = 2
HEALTH_REGEN = 1
COLOR_PLAYER = (123, 123, 123)

# Анимации
JUMP_DURATION = 0.3
DASH_DURATION = 0.15
DASH_COOLDOWN = 0.45
DASH_DISTANCE = 110
ATTACK_DURATION = 0.2
ATTACK_COOLDOWN = 0.1
HURT_DURATION = 0.2

# Физика
GRAVITY = 0
JUMP_HEIGHT = 40
